# Generated by Django 4.2.9 on 2024-01-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='image',
            field=models.CharField(default=1, max_length=2083),
            preserve_default=False,
        ),
    ]
