# Generated by Django 4.2.9 on 2024-01-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baking', '0002_bakery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakery',
            name='price',
            field=models.FloatField(),
        ),
    ]
